name: hello world
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  printing-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: printing hello world
        run: echo "Hello world"
